// Generated by https://quicktype.io

export interface CV {
  basics: Basics;
  workExperience: WorkExperience[];
  education: Education[];
  projects: Project[];
  skills: Skill[];
  interests: Interest[];
}

export interface Basics {
  name: string;
  jobTitle: string;
  email: string;
  phone: string;
  website: string;
  summary: string;
  location: Location;
  profiles: Profile[];
}

export interface Location {
  city: string;
  country: string;
}

export interface Profile {
  name: string;
  url: string;
}

export interface Education {
  institutionName: string;
  qualification: string;
  grade: string;
  dateFrom: string;
  dateTo: string;
}

export interface Interest {
  interestTitle: string;
  interestSummary: string;
  interestSkills: any[];
}

export interface Project {
  title: string;
  keyPoints: any[];
  keyWords: any[];
}

export interface Skill {
  categoryTitle: string;
  categorySkills: CategorySkills;
}

export interface CategorySkills {
  skillName: string;
  skillRating: string;
}

export interface WorkExperience {
  role: string;
  company: Company;
  dateFrom: string;
  dateTo: string;
  summary: string;
  keyPoints: any[];
  skills: any[];
}

export interface Company {
  name: string;
  description: string;
  logoSrc: string;
}
